# palam等级 → source修正权重表
# 语义：正系数 = 增加对应source；负系数 = 扣减对应source（扣减不越过0，与旧版min语义等价）
# 数值与旧版 game_engine/data_pipeline/palam/palam2src.py 逐项一致

# palam等级规则
PALAM_LV: dict[int, int] = {
    1: 100,
    2: 200,
    3: 500,
    4: 1000,
    5: 2000,
    6: 5000,
    7: 10_000,
    8: 20_000,
    9: 50_000,
    10: 100_000,
    11: 200_000,
    12: 500_000,
    13: 1_000_000,
    14: 2_000_000,
    15: 5_000_000,
    16: 10_000_000,
    17: 20_000_000,
    18: 50_000_000,
    19: 100_000_000,
    20: 200_000_000,
    21: 500_000_000,
    22: 1_000_000_000,
    23: 2_000_000_000,
    24: 5_000_000_000,
    25: 10_000_000_000
}

PALAM2SRC_WEIGHTS: dict[str, dict[str, int]] = {
    # ---- 快感系：5个pleasure palam 同构，主修对应快感 + 润滑/情爱等 ----
    'c_pleasure_palam': {
        'c_pleasure_source': 4,
        'lubrication_source': 3,
        'love_source': 2,
        'sex_act_source': 2,
        'lust_source': 2,
        'obedience_source': 2,
        'submission_source': 2,
        'happiness_source': 3,
        'conquest_source': 2,
        'exposure_source': 2,
        'passivity_source': 2,
        'achievement_source': 2,
        'pain_source': -1,
        'fear_source': -1,
        'disgust_source': -1,
        'unclean_source': -1,
        'depression_source': -1,
        'escape_source': -1,
    },
    'v_pleasure_palam': {
        'v_pleasure_source': 4,
        'lubrication_source': 3,
        'love_source': 2,
        'sex_act_source': 2,
        'lust_source': 2,
        'obedience_source': 2,
        'submission_source': 2,
        'happiness_source': 3,
        'conquest_source': 2,
        'exposure_source': 2,
        'passivity_source': 2,
        'achievement_source': 2,
        'pain_source': -1,
        'fear_source': -1,
        'disgust_source': -1,
        'unclean_source': -1,
        'depression_source': -1,
        'escape_source': -1,
    },
    'a_pleasure_palam': {
        'a_pleasure_source': 4,
        'lubrication_source': 3,
        'love_source': 2,
        'sex_act_source': 2,
        'lust_source': 2,
        'obedience_source': 2,
        'submission_source': 2,
        'happiness_source': 3,
        'conquest_source': 2,
        'exposure_source': 2,
        'passivity_source': 2,
        'achievement_source': 2,
        'pain_source': -1,
        'fear_source': -1,
        'disgust_source': -1,
        'unclean_source': -1,
        'depression_source': -1,
        'escape_source': -1,
    },
    'b_pleasure_palam': {
        'b_pleasure_source': 4,
        'lubrication_source': 3,
        'love_source': 2,
        'sex_act_source': 2,
        'lust_source': 2,
        'obedience_source': 2,
        'submission_source': 2,
        'happiness_source': 3,
        'conquest_source': 2,
        'exposure_source': 2,
        'passivity_source': 2,
        'achievement_source': 2,
        'pain_source': -1,
        'fear_source': -1,
        'disgust_source': -1,
        'unclean_source': -1,
        'depression_source': -1,
        'escape_source': -1,
    },
    'm_pleasure_palam': {
        'm_pleasure_source': 4,
        'lubrication_source': 3,
        'love_source': 2,
        'sex_act_source': 2,
        'lust_source': 2,
        'obedience_source': 2,
        'submission_source': 2,
        'happiness_source': 3,
        'conquest_source': 2,
        'exposure_source': 2,
        'passivity_source': 2,
        'achievement_source': 2,
        'pain_source': -1,
        'fear_source': -1,
        'disgust_source': -1,
        'unclean_source': -1,
        'depression_source': -1,
        'escape_source': -1,
    },
    # ---- 润滑 ----
    'lubrication_palam': {
        'c_pleasure_source': 3,
        'v_pleasure_source': 3,
        'a_pleasure_source': 3,
        'b_pleasure_source': 3,
    },
    # ---- 恭顺 ----
    'obedience_palam': {
        'love_source': 3,
        'obedience_source': 4,
        'submission_source': 2,
        'conquest_source': 3,
        'fear_source': -1,
        'escape_source': -1,
        'disgust_source': -1,
    },
    # ---- 欲情 ----
    'lust_palam': {
        'c_pleasure_source': 2,
        'v_pleasure_source': 2,
        'a_pleasure_source': 2,
        'b_pleasure_source': 2,
        'm_pleasure_source': 2,
        'love_source': 2,
        'sex_act_source': 2,
        'lust_source': 4,
        'obedience_source': 2,
        'submission_source': 2,
        'happiness_source': 2,
        'conquest_source': 1,
        'exposure_source': 1,
        'passivity_source': 1,
        'achievement_source': 1,
        'lubrication_source': 2,
        'pain_source': -1,
        'fear_source': -1,
        'escape_source': -1,
        'disgust_source': -1,
        'unclean_source': -1,
        'depression_source': -1,
    },
    # ---- 屈服 ----
    'submission_palam': {
        'sex_act_source': 2,
        'lust_source': 2,
        'obedience_source': 3,
        'submission_source': 4,
        'conquest_source': 3,
        'passivity_source': 3,
        'achievement_source': 3,
        'fear_source': -1,
        'escape_source': -2,
        'disgust_source': -1,
        'unclean_source': -1,
        'depression_source': -1,
    },
    # ---- 习得 ----
    'learn_palam': {
        'sex_act_source': 2,
        'obedience_source': 2,
        'conquest_source': 2,
        'achievement_source': 3,
    },
    # ---- 羞耻 ----
    'shame_palam': {
        'c_pleasure_source': 1,
        'v_pleasure_source': 1,
        'a_pleasure_source': 1,
        'b_pleasure_source': 1,
        'm_pleasure_source': 1,
        'lust_source': 2,
        'obedience_source': 2,
        'submission_source': 2,
        'happiness_source': 1,
        'conquest_source': 1,
        'passivity_source': 3,
        'achievement_source': 1,
        'escape_source': 1,
        'disgust_source': 1,
        'exposure_source': -1,
    },
    # ---- 苦痛 ----
    'pain_palam': {
        'pain_source': 3,
        'fear_source': 3,
        'submission_source': 3,
        'conquest_source': 3,
        'passivity_source': 3,
        'depression_source': 3,
        'escape_source': 4,
        'disgust_source': 3,
        'c_pleasure_source': -3,
        'v_pleasure_source': -3,
        'a_pleasure_source': -3,
        'b_pleasure_source': -3,
        'm_pleasure_source': -3,
        'lust_source': -2,
        'obedience_source': -3,
        'exposure_source': -1,
        'lubrication_source': -1,
        'love_source': -3,
        'achievement_source': -2,
        'happiness_source': -3,
    },
    # ---- 恐怖 ----
    'fear_palam': {
        'pain_source': 3,
        'fear_source': 4,
        'obedience_source': 2,
        'submission_source': 3,
        'conquest_source': 4,
        'passivity_source': 3,
        'depression_source': 3,
        'escape_source': 4,
        'disgust_source': 3,
        'c_pleasure_source': -2,
        'v_pleasure_source': -2,
        'a_pleasure_source': -2,
        'b_pleasure_source': -2,
        'm_pleasure_source': -2,
        'lubrication_source': -1,
        'love_source': -3,
        'achievement_source': -2,
        'lust_source': -2,
        'exposure_source': -1,
        'happiness_source': -3,
    },
    # ---- 好意 ----
    'kindness_palam': {
        'c_pleasure_source': 2,
        'v_pleasure_source': 2,
        'a_pleasure_source': 2,
        'b_pleasure_source': 2,
        'm_pleasure_source': 2,
        'love_source': 3,
        'achievement_source': 2,
        'lust_source': 2,
        'obedience_source': 2,
        'submission_source': 2,
        'happiness_source': 3,
        'conquest_source': 1,
        'passivity_source': 1,
        'pain_source': -2,
        'fear_source': -2,
        'unclean_source': -1,
        'disgust_source': -2,
        'escape_source': -1,
        'depression_source': -2,
    },
    # ---- 优越 ----
    'superiority_palam': {
        'happiness_source': 1,
        'depression_source': 1,
        'fear_source': -1,
        'obedience_source': -1,
        'submission_source': -1,
        'conquest_source': -2,
        'passivity_source': -2,
        'escape_source': -1,
    },
    # ---- 反感 ----
    'disgust_palam': {
        'fear_source': 1,
        'depression_source': 3,
        'escape_source': 3,
        'disgust_source': 4,
        'c_pleasure_source': -1,
        'v_pleasure_source': -1,
        'a_pleasure_source': -1,
        'b_pleasure_source': -1,
        'm_pleasure_source': -1,
        'lubrication_source': -1,
        'love_source': -3,
        'achievement_source': -2,
        'lust_source': -2,
        'obedience_source': -3,
        'exposure_source': -1,
        'submission_source': -2,
        'happiness_source': -3,
        'conquest_source': -2,
    },
    # ---- 不快 ----
    'unhappiness_palam': {
        'fear_source': 1,
        'depression_source': 3,
        'escape_source': 3,
        'disgust_source': 4,
        'c_pleasure_source': -3,
        'v_pleasure_source': -3,
        'a_pleasure_source': -3,
        'b_pleasure_source': -3,
        'm_pleasure_source': -3,
        'lubrication_source': -1,
        'love_source': -3,
        'achievement_source': -2,
        'lust_source': -2,
        'obedience_source': -3,
        'exposure_source': -1,
        'submission_source': -2,
        'happiness_source': -3,
        'conquest_source': -2,
    },
    # ---- 抑郁 ----
    'depression_palam': {
        'fear_source': 2,
        'passivity_source': 1,
        'depression_source': 4,
        'escape_source': 2,
        'disgust_source': 3,
        'c_pleasure_source': -3,
        'v_pleasure_source': -3,
        'a_pleasure_source': -3,
        'b_pleasure_source': -3,
        'm_pleasure_source': -3,
        'lubrication_source': -1,
        'love_source': -3,
        'sex_act_source': -1,
        'achievement_source': -2,
        'lust_source': -2,
        'obedience_source': -2,
        'exposure_source': -1,
        'submission_source': -2,
        'happiness_source': -3,
        'conquest_source': -2,
    },
}

ORGASM_BASE = {
    'c_pleasure_palam': [15_000, 30_000, 80_000, 150_000],
    'v_pleasure_palam': [15_000, 30_000, 80_000, 150_000],
    'a_pleasure_palam': [30_000, 80_000, 150_000, 250_000],
    'b_pleasure_palam': [15_000, 30_000, 80_000, 150_000],
    'm_pleasure_palam': [15_000, 30_000, 80_000, 150_000]
}

ORGASM_NUM_CN = {
    2: '二重',
    3: '三重',
    4: '四重',
    5: '五重'
}

ORGASM_LV_CN = {
    1: '绝顶',
    2: '强绝顶',
    3: '超强绝顶',
    4: '最强绝顶'
}

ORGASM_NUM_JUEL_MODIFIER = {
    2: 1.5,
    3: 2.0,
    4: 2.5,
    5: 3.0
}

ORGASM_LV_JUEL_MODIFIER = {
    1: 1.0,
    2: 1.5,
    3: 2.0,
    4: 2.5
}
# 玩家射精闭环配置
EJACULATION_THRESHOLD: int = 5000
EJACULATION_VITALITY_COST: int = 200
SEMEN_SOURCES: dict[str, dict[str, int]] = {
    '中出': {
        'v_pleasure_source': 500,
        'lust_source': 300,
        'submission_source': 300,
        'unclean_source': 300,
    },
}